# **Parte 1: Diagnóstico**

1. Lectura y documentación inicial: 
    - Carga el dataset en R/Python.
    - ¿Cuántas observaciones y variables hay?
    - ¿Cuántas variables son categóricas y cuántas numéricas?
    - ¿Hay alguna variable que pueda ser un ID?

2. Diagnóstico exploratorio:
    - Describe al menos 2 variables numéricas con media, min y max. 
    - Describe al menos 2 variables categóricas con sus frecuencias.

3. Conclusiones exploratorias:
    - Extrae al menos 5 hallazgos interesantes con visualizaciones que los respalden (usa  tablas cruzadas, ggplot2, tableone, etc.).

### **0: Dependencias**

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

### **1. Lectura y documentación inicial**

##### 1.1: Carga del dataset en Python

In [3]:
# Cargamos los datos del archivo CSV en un DataFrame de pandas
path = "/home/yagoh/Escritorio/Personal/dev/Educacion/Diplomado-Tecnicas-Estadisticas-y-Mineria-de-Datos/Unidad_3/Data/netflix-rotten-tomatoes-metacritic-imdb-netflix-rotten-tomatoes-metacritic-imdb.csv"
df = pd.read_csv(path)

# Vemos las primeras filas
df.head(1)

,Title,Genre,Tags,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,...,Netflix Release Date,Production House,Netflix Link,IMDb Link,Summary,IMDb Votes,Image,Poster,TMDb Trailer,Trailer Site
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Comedy Programmes,Romantic TV Comedies,Horror ...","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,...,2021-03-04,"Canal+, Sandrew Metronome",https://www.netflix.com/watch/81415947,https://www.imdb.com/title/tt1139797,A med student with a supernatural gift tries t...,205926.0,https://occ-0-4708-64.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BOWM4NT...,NaN,NaN

##### 1.2: ¿Cuántas observaciones y variables hay?

In [4]:
observaciones, variables = df.shape

print(f"El dataset tiene {observaciones} observaciones y {variables} variables.")

El dataset tiene 15480 observaciones y 29 variables.

##### 1.3: ¿Cuántas variables son categóricas y cuántas numéricas?

In [5]:
# Podemos hacer una primera exploración usando .describe(), ya que nos da un resumen estadístico de las variables numéricas del DataFrame.
df.describe()

,Hidden Gem Score,IMDb Score,Rotten Tomatoes Score,Metacritic Score,Awards Received,Awards Nominated For,IMDb Votes
count,13379.000000,13381.000000,6382.000000,4336.000000,6075.000000,7661.000000,1.337900e+04
mean,5.937551,6.496054,59.523034,56.813653,8.764444,13.983161,4.272841e+04
std,2.250202,1.146910,26.999173,17.582545,18.311171,29.821052,1.257012e+05
min,0.600000,1.000000,0.000000,5.000000,1.000000,1.000000,5.000000e+00
25%,3.800000,5.800000,38.000000,44.000000,1.000000,2.000000,4.035000e+02
50%,6.800000,6.600000,64.000000,57.000000,3.000000,5.000000,2.322000e+03
75%,7.900000,7.300000,83.000000,70.000000,8.000000,12.000000,2.089050e+04
max,9.800000,9.700000,100.000000,100.000000,300.000000,386.000000,2.354197e+06

In [6]:
# Veamos si estas columnas en verdad son numéricas.

df[["Hidden Gem Score", "IMDb Score", "Rotten Tomatoes Score", "Metacritic Score", "Awards Received", "Awards Nominated For", "IMDb Votes"]]

,Hidden Gem Score,IMDb Score,Rotten Tomatoes Score,Metacritic Score,Awards Received,Awards Nominated For,IMDb Votes
0,4.3,7.9,98.0,82.0,74.0,57.0,205926.0
1,7.0,5.8,79.0,69.0,1.0,NaN,2838.0
2,6.4,4.3,NaN,46.0,NaN,NaN,1720.0
3,7.7,6.5,NaN,NaN,1.0,NaN,1147.0
4,8.1,6.3,NaN,NaN,NaN,4.0,63.0
...,...,...,...,...,...,...,...
15475,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15476,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15477,8.4,6.8,NaN,NaN,NaN,NaN,71.0
15478,8.2,6.4,NaN,NaN,NaN,NaN,82.0
15479,8.1,6.2,NaN,NaN,NaN,NaN,17.0

In [21]:
# En efecto, son variables numéricas, pero esto no nos garantiza que no haya otras variables que sean numéricas pero que no estén en el formato correcto.

columnas = df.columns

for columna in columnas:
    print(50*"=")
    print(f"Columna: {columna}")
    print(f"Valor: {df[df[columna].notna()][columna][:1]}")
    print(f"Tipo de dato: {type(df[columna][0])}")
    print(50*"=")

==================================================
Columna: Title
Valor: 0    Lets Fight Ghost
Name: Title, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Genre
Valor: 0    Crime, Drama, Fantasy, Horror, Romance
Name: Genre, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Tags
Valor: 0    Comedy Programmes,Romantic TV Comedies,Horror ...
Name: Tags, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Languages
Valor: 0    Swedish, Spanish
Name: Languages, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Series or Movie
Valor: 0    Series
Name: Series or Movie, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Hidden Gem Score
Valor: 0    4.3
Name: Hidden Gem Score, dtype: float64
Tipo de dato: <class 'numpy.float64'>
==================================================
==================================================
Columna: Country Availability
Valor: 0    Thailand
Name: Country Availability, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Runtime
Valor: 0    < 30 minutes
Name: Runtime, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Director
Valor: 0    Tomas Alfredson
Name: Director, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Writer
Valor: 0    John Ajvide Lindqvist
Name: Writer, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Actors
Valor: 0    Kåre Hedebrant, Per Ragnar, Lina Leandersson, ...
Name: Actors, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: View Rating
Valor: 0    R
Name: View Rating, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: IMDb Score
Valor: 0    7.9
Name: IMDb Score, dtype: float64
Tipo de dato: <class 'numpy.float64'>
==================================================
==================================================
Columna: Rotten Tomatoes Score
Valor: 0    98.0
Name: Rotten Tomatoes Score, dtype: float64
Tipo de dato: <class 'numpy.float64'>
==================================================
==================================================
Columna: Metacritic Score
Valor: 0    82.0
Name: Metacritic Score, dtype: float64
Tipo de dato: <class 'numpy.float64'>
==================================================
==================================================
Columna: Awards Received
Valor: 0    74.0
Name: Awards Received, dtype: float64
Tipo de dato: <class 'numpy.float64'>
==================================================
==================================================
Columna: Awards Nominated For
Valor: 0    57.0
Name: Awards Nominated For, dtype: float64
Tipo de dato: <class 'numpy.float64'>
==================================================
==================================================
Columna: Boxoffice
Valor: 0    $2,122,065
Name: Boxoffice, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Release Date
Valor: 0    12 Dec 2008
Name: Release Date, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Netflix Release Date
Valor: 0    2021-03-04
Name: Netflix Release Date, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Production House
Valor: 0    Canal+, Sandrew Metronome
Name: Production House, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Netflix Link
Valor: 0    https://www.netflix.com/watch/81415947
Name: Netflix Link, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: IMDb Link
Valor: 0    https://www.imdb.com/title/tt1139797
Name: IMDb Link, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Summary
Valor: 0    A med student with a supernatural gift tries t...
Name: Summary, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: IMDb Votes
Valor: 0    205926.0
Name: IMDb Votes, dtype: float64
Tipo de dato: <class 'numpy.float64'>
==================================================
==================================================
Columna: Image
Valor: 0    https://occ-0-4708-64.1.nflxso.net/dnm/api/v6/...
Name: Image, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: Poster
Valor: 0    https://m.media-amazon.com/images/M/MV5BOWM4NT...
Name: Poster, dtype: str
Tipo de dato: <class 'str'>
==================================================
==================================================
Columna: TMDb Trailer
Valor: 1    https://www.youtube.com/watch?v=eIbcxPy4okQ
Name: TMDb Trailer, dtype: str
Tipo de dato: <class 'float'>
==================================================
==================================================
Columna: Trailer Site
Valor: 1    YouTube
Name: Trailer Site, dtype: str
Tipo de dato: <class 'float'>
==================================================

In [22]:
# Vemos que la variable Boxoffice, que es numérica, no está en el formato correcto. Esto se debe a que tiene un símbolo de dólar y una coma, lo que hace que pandas la lea como un objeto (string) en lugar de un número.

df["Boxoffice"] = df["Boxoffice"].str.replace("$", "").str.replace(",", "").astype(float)
df["Boxoffice"].head(1)

0    2122065.0
Name: Boxoffice, dtype: float64

In [30]:
# Una vez corregido, ya tenemos todas las variables numéricas.
universo = set(df.columns)
numericas = set(df.describe().columns)
categoricas = universo - numericas

print(f"Variables numéricas:\n{numericas} \n\nVariables categóricas:\n{categoricas}")

Variables numéricas:
{'Boxoffice', 'Metacritic Score', 'Awards Received', 'Hidden Gem Score', 'IMDb Votes', 'IMDb Score', 'Awards Nominated For', 'Rotten Tomatoes Score'}

Variables categóricas:
{'Writer', 'Summary', 'Image', 'Netflix Release Date', 'Runtime', 'Title', 'Country Availability', 'Tags', 'Director', 'Actors', 'Trailer Site', 'Languages', 'Poster', 'Genre', 'View Rating', 'Netflix Link', 'Production House', 'IMDb Link', 'Release Date', 'TMDb Trailer', 'Series or Movie'}

##### 1.4. ¿Hay alguna variable que pueda ser un ID?

In [31]:
# Propongo que la variable "Title" sea nuestro id, vamos a comprobarlo.

print(f"Cantidad de títulos: {df['Title'].nunique()}")

Cantidad de títulos: 15071

In [32]:
df["Title"].isnull().sum()

np.int64(0)

In [37]:
# Si hay nombres repetidos, entonces no podemos usar esta variable como id.

# Veremos si hay alguna columna que no tenga repetidos ni nulos, y que por lo tanto pueda ser nuestro id.
for col in df.columns:
    if df[col].isnull().sum() == 0 and df[col].nunique() == len(df):
        print(f"La columna {col} puede ser nuestro id.")

La columna Netflix Link puede ser nuestro id.

### **2. Diagnóstico exploratorio**

##### 2.1: Describe al menos 2 variables numéricas con media, min y max.

In [47]:
# Voy a escoger las variables Boxoffice y IMDb Score

df[["Boxoffice", "IMDb Score"]].describe().loc[["mean", "min", "max"]].style.format('{:,.2f}')

##### 2.2: Describe al menos 2 variables categóricas con sus frecuencias.

In [57]:
df[["Genre", "Languages"]].describe()

         Genre Languages
count    13770     13526
unique    1780      1437
top     Comedy   English
freq      1186      5133